### ISSUE TITLE
Bug: Errors in log when sending notifications

### ISSUE THREAD

**Issue by andrewminer** [pinerylabs/project-management#204]
While the emails did eventually get through, these errors appear in the log, and probably should get some attention to figure out what's up:

```
2020-12-23T21:43:28.066486+00:00 app[web.1]: [INFO] Processing Notification<1> for sending as email...
2020-12-23T21:43:28.067351+00:00 app[web.1]: [INFO] >>> Sending mail to ['info+delta@runbooks.app'] with template: 1726269
2020-12-23T21:43:28.245682+00:00 app[web.1]: [ERRO] worker EmailWorker encountered an unexpected error:
2020-12-23T21:43:28.245687+00:00 app[web.1]: [ERRO] Traceback (most recent call last):
2020-12-23T21:43:28.245688+00:00 app[web.1]: [ERRO]   File "/app/src/python/pinerylabs/util/worker.py", line 169, in _run
2020-12-23T21:43:28.245688+00:00 app[web.1]: [ERRO]     result = self.perform_work()
2020-12-23T21:43:28.245689+00:00 app[web.1]: [ERRO]   File "/app/src/python/pinerylabs/runbooks/workers/email_worker.py", line 44, i
2020-12-23T21:43:28.245693+00:00 app[web.1]: [ERRO]       n perform_work
2020-12-23T21:43:28.245693+00:00 app[web.1]: [ERRO]     with notification.locked():
2020-12-23T21:43:28.245694+00:00 app[web.1]: [ERRO]   File "/app/.heroku/python/lib/python3.7/contextlib.py", line 112, in __enter__
2020-12-23T21:43:28.245694+00:00 app[web.1]: [ERRO]     return next(self.gen)
2020-12-23T21:43:28.245694+00:00 app[web.1]: [ERRO]   File "/app/src/python/pinerylabs/orm/model.py", line 399, in locked
2020-12-23T21:43:28.245695+00:00 app[web.1]: [ERRO]     raise RuntimeError(f"failed to obtain lock on {self} within {max_wait}s")
2020-12-23T21:43:28.245695+00:00 app[web.1]: [ERRO] RuntimeError: failed to obtain lock on Notification(id=1, channel="email", event
2020-12-23T21:43:28.245696+00:00 app[web.1]: [ERRO]     _id=26, kind="new-runlog", locked_at=2020-12-23 21:43:28.048925, natural_key
2020-12-23T21:43:28.245696+00:00 app[web.1]: [ERRO]     ="new-runlog|email|runlog.id:10|user.id:2", payload_json="{"runlog_name": "v
2020-12-23T21:43:28.245696+00:00 app[web.1]: [ERRO]     1.0 assignment sampler test", "runlog_url": "https://staging.runbooks.app/us
2020-12-23T21:43:28.245697+00:00 app[web.1]: [ERRO]     ers/bravo-charlie/runs/v1-0-assignment-sampler-test", "template_id": 1726269
2020-12-23T21:43:28.245697+00:00 app[web.1]: [ERRO]     , "user_email_address": "info+delta@runbooks.app", "user_name": "Delta Echo"
2020-12-23T21:43:28.245698+00:00 app[web.1]: [ERRO]     }", sent_at=None, target_user_id=2) within 10.0s
2020-12-23T21:43:28.542621+00:00 app[web.1]: [INFO] <<< Email sent to ['info+delta@runbooks.app'] with template: 1726269 in 473ms
2020-12-23T21:43:28.573623+00:00 app[web.1]: [INFO] More work is expected, so only sleeping for 0.61s...
2020-12-23T21:44:20.075674+00:00 app[web.1]: [INFO] >>> GET /api/users
2020-12-23T21:44:20.075692+00:00 app[web.1]: [INFO]     args:
2020-12-23T21:44:20.075693+00:00 app[web.1]: [INFO]         graph: full
2020-12-23T21:44:20.075693+00:00 app[web.1]: [INFO]         slug: current
2020-12-23T21:44:20.095417+00:00 app[web.1]: [INFO] >>> GET /api/runlogs
2020-12-23T21:44:20.095419+00:00 app[web.1]: [INFO]     args:
2020-12-23T21:44:20.095419+00:00 app[web.1]: [INFO]         user_slug: bravo-charlie
2020-12-23T21:44:20.095420+00:00 app[web.1]: [INFO]         runlog_slug: v1-0-assignment-sampler-test
2020-12-23T21:44:20.095420+00:00 app[web.1]: [INFO]         graph: full
2020-12-23T21:44:20.460422+00:00 app[web.1]: [ERRO] API request yielded an unexpected error:
2020-12-23T21:44:20.460431+00:00 app[web.1]: [ERRO]     Traceback (most recent call last):
2020-12-23T21:44:20.460432+00:00 app[web.1]: [ERRO]       File "/app/src/python/pinerylabs/runbooks/apiserver/web/route_conditions.p
2020-12-23T21:44:20.460432+00:00 app[web.1]: [ERRO]           y", line 38, in wrapped_view
2020-12-23T21:44:20.460432+00:00 app[web.1]: [ERRO]         value = view(*args, **kwargs)
2020-12-23T21:44:20.460433+00:00 app[web.1]: [ERRO]       File "/app/src/python/pinerylabs/runbooks/apiserver/blueprints/runlogs.py"
2020-12-23T21:44:20.460433+00:00 app[web.1]: [ERRO]           , line 39, in find_runlogs
2020-12-23T21:44:20.460434+00:00 app[web.1]: [ERRO]         runlogs = list(g.box.runlogs.find_by_slug(args.user_slug, args.runlog_sl
2020-12-23T21:44:20.460434+00:00 app[web.1]: [ERRO]             ug))
2020-12-23T21:44:20.460435+00:00 app[web.1]: [ERRO]       File "/app/src/python/pinerylabs/orm/model_box.py", line 454, in select_qu
2020-12-23T21:44:20.460435+00:00 app[web.1]: [ERRO]           ery
2020-12-23T21:44:20.460435+00:00 app[web.1]: [ERRO]         if result.can_read:
2020-12-23T21:44:20.460436+00:00 app[web.1]: [ERRO]       File "/app/src/python/pinerylabs/orm/model.py", line 92, in can_read
2020-12-23T21:44:20.460436+00:00 app[web.1]: [ERRO]         return self.box.can_read(self.id)
2020-12-23T21:44:20.460437+00:00 app[web.1]: [ERRO]       File "/app/src/python/pinerylabs/runbooks/models/runlog.py", line 116, in
2020-12-23T21:44:20.460437+00:00 app[web.1]: [ERRO]           can_read
2020-12-23T21:44:20.460437+00:00 app[web.1]: [ERRO]         viewer = self.derive_viewer(viewer)
2020-12-23T21:44:20.460438+00:00 app[web.1]: [ERRO]       File "/app/src/python/pinerylabs/orm/model_box.py", line 531, in derive_vi
2020-12-23T21:44:20.460438+00:00 app[web.1]: [ERRO]           ewer
2020-12-23T21:44:20.460439+00:00 app[web.1]: [ERRO]         raise RuntimeError("cannot assess permissions because this model box has
2020-12-23T21:44:20.460439+00:00 app[web.1]: [ERRO]              no viewer")
2020-12-23T21:44:20.460439+00:00 app[web.1]: [ERRO]     RuntimeError: cannot assess permissions because this model box has no viewer
2020-12-23T21:44:20.460440+00:00 app[web.1]: [ERRO]
2020-12-23T21:44:20.488946+00:00 app[web.1]: [INFO] <<< GET /api/runlogs: 500 INTERNAL SERVER ERROR with 160b in 393ms
```

Even worse, they still seem to get marked as sent in the database:

```
id             | 3
channel        | email
event_id       | 28
kind           | runlog-step-complete
locked_at      |
natural_key    | runlog-step-complete|email|runlog_steps.id:65|user.id:2
payload_json   | {"runlog_name": "v1.0 assignment sampler test", "runlog_step_title": "Step 1", "runlog_step_url": "https://staging.runbooks.app/users/bravo-charlie/runs/v1-0-assignment-sampler-test?step-id=65", "template_id": 1742817, "user_email_address": "info+delta@runbooks.app", "user_name": "Delta Echo"}
sent_at        | 2020-12-23 21:47:33.752563
target_user_id | 2
```

**Comment by andrewminer** [comment]
I've updated both staging and production environments to use a Papertrail add-on.  Both have been configured to report errors via email.  That should suffice for now.
