### ISSUE TITLE
Bug: No viewer error in production

### ISSUE THREAD

**Issue by andrewminer** [pinerylabs/project-management#279]
```
 Feb 05 04:29:32 at=info method=GET path="/api/runbooks?team_slug=vaibhav&runbook_slug=untitled-runbook-2&graph=full" host=api.runbooks.app request_id=0907c632-bacc-41a4-b2dd-8212a79a4224 fwd="122.167.16.113" dyno=web.1 connect=1ms service=60ms status=500 bytes=574 protocol=https
Feb 05 04:29:32 MainThread [INFO] >>> GET /api/runbooks?team_slug=vaibhav&runbook_slug=untitled-runbook-2&graph=fu
Feb 05 04:29:32 MainThread [INFO]     ll 
Feb 05 04:29:32 MainThread [ERRO] API request yielded an unexpected error:
Feb 05 04:29:32 MainThread [ERRO]     Traceback (most recent call last):
Feb 05 04:29:32 MainThread [ERRO]       File "/app/src/python/pinerylabs/runbooks/apiserver/web/route_conditions.p
Feb 05 04:29:32 MainThread [ERRO]           y", line 41, in wrapped_view
Feb 05 04:29:32 MainThread [ERRO]         value = view(*args, **kwargs)
Feb 05 04:29:32 MainThread [ERRO]       File "/app/src/python/pinerylabs/runbooks/apiserver/blueprints/runbooks.py
Feb 05 04:29:32 MainThread [ERRO]           ", line 58, in find_runbooks
Feb 05 04:29:32 MainThread [ERRO]         runbook.load_graph(graph)
Feb 05 04:29:32 MainThread [ERRO]       File "/app/src/python/pinerylabs/orm/model.py", line 320, in load_graph
Feb 05 04:29:32 MainThread [ERRO]         if not self._load_graph(graph_type):
Feb 05 04:29:32 MainThread [ERRO]       File "/app/src/python/pinerylabs/runbooks/models/runbook.py", line 225, in
Feb 05 04:29:32 MainThread [ERRO]            _load_graph
Feb 05 04:29:32 MainThread [ERRO]         if self.owner is not None:
Feb 05 04:29:32 MainThread [ERRO]       File "/app/src/python/pinerylabs/runbooks/models/runbook.py", line 164, in
Feb 05 04:29:32 MainThread [ERRO]            owner
Feb 05 04:29:32 MainThread [ERRO]         return self.get_child("owner", lambda: self.box.team_members.read(self.o
Feb 05 04:29:32 MainThread [ERRO]             wner_id))
Feb 05 04:29:32 MainThread [ERRO]       File "/app/src/python/pinerylabs/orm/model.py", line 540, in get_child
Feb 05 04:29:32 MainThread [ERRO]         self._children[field_name] = doLoad()
Feb 05 04:29:32 MainThread [ERRO]       File "/app/src/python/pinerylabs/runbooks/models/runbook.py", line 164, in
Feb 05 04:29:32 MainThread [ERRO]            <lambda>
Feb 05 04:29:32 MainThread [ERRO]         return self.get_child("owner", lambda: self.box.team_members.read(self.o
Feb 05 04:29:32 MainThread [ERRO]             wner_id))
Feb 05 04:29:32 MainThread [ERRO]       File "/app/src/python/pinerylabs/orm/model_box.py", line 380, in read
Feb 05 04:29:32 MainThread [ERRO]         return self.new(model_id).read()
Feb 05 04:29:32 MainThread [ERRO]       File "/app/src/python/pinerylabs/orm/model.py", line 433, in read
Feb 05 04:29:32 MainThread [ERRO]         if not self.can_read:
Feb 05 04:29:32 MainThread [ERRO]       File "/app/src/python/pinerylabs/orm/model.py", line 94, in can_read
Feb 05 04:29:32 MainThread [ERRO]         return self.box.can_read(self.id)
Feb 05 04:29:32 MainThread [ERRO]       File "/app/src/python/pinerylabs/runbooks/models/team_member.py", line 84,
Feb 05 04:29:32 MainThread [ERRO]            in can_read
Feb 05 04:29:32 MainThread [ERRO]         viewer = self.derive_viewer(user)
Feb 05 04:29:32 MainThread [ERRO]       File "/app/src/python/pinerylabs/orm/model_box.py", line 588, in derive_vi
Feb 05 04:29:32 MainThread [ERRO]           ewer
Feb 05 04:29:32 MainThread [ERRO]         raise RuntimeError("cannot assess permissions because this model box has
Feb 05 04:29:32 MainThread [ERRO]              no viewer")
Feb 05 04:29:32 MainThread [ERRO]     RuntimeError: cannot assess permissions because this model box has no viewer
Feb 05 04:29:32 MainThread [ERRO]     
Feb 05 04:29:32 MainThread [INFO] <<< GET /api/runbooks: 500 INTERNAL SERVER ERROR with 174b in 55ms
```

**Comment by andrewminer** [comment]
### STEPS

1. Reload seed data
2. Log in as `info+bravo@runbooks.app`
3. Update the latest session for that user to set the `expiration_date` to something in the past.
4. Dismiss the tutorial step displayed on the dashboard

### EXPECTED

The user should be sent directly back to the login page, and once they log in again, returned to the page where they started.

### ACTUAL

An error dialog is shown with a 500 error.

### DIAGNOSIS

In `route_conditions.py`, the function which searches for the user never does check that it's call to `g.box.users.find_by_session` actually finds a user.  Nor does anything else downstream.  Nor does anything downstream catch the `RuntimeError` raised by `ModelBox` when asked to check permissions without a valid user.
