### ISSUE TITLE
Bug: Server error whenever a user with an expired session visits a page

### ISSUE THREAD

**Issue by andrewminer** [pinerylabs/project-management#283]
The following log trace occurred when I attempted to visit Runbooks after having been away long enough for my session to have expired.  No problem was ever reported to the user.

```
Apr 28 10:26:22 MainThread [INFO] >>> GET /api/users?graph=full&slug=current 
Apr 28 10:26:22 MainThread [INFO] >>> GET /api/teams?slug=stockx&graph=full 
Apr 28 10:26:22 MainThread [ERRO] API request yielded an unexpected error:
Apr 28 10:26:22 MainThread [ERRO]     Traceback (most recent call last):
Apr 28 10:26:22 MainThread [ERRO]       File "/app/src/python/pinerylabs/runbooks/apiserver/web/route_conditions.p
Apr 28 10:26:22 MainThread [ERRO]           y", line 41, in wrapped_view
Apr 28 10:26:22 MainThread [ERRO]         value = view(*args, **kwargs)
Apr 28 10:26:22 MainThread [ERRO]       File "/app/src/python/pinerylabs/runbooks/apiserver/blueprints/teams.py", 
Apr 28 10:26:22 MainThread [ERRO]           line 34, in find_teams
Apr 28 10:26:22 MainThread [ERRO]         team.load_graph(graph)
Apr 28 10:26:22 MainThread [ERRO]       File "/app/src/python/pinerylabs/orm/model.py", line 320, in load_graph
Apr 28 10:26:22 MainThread [ERRO]         if not self._load_graph(graph_type):
Apr 28 10:26:22 MainThread [ERRO]       File "/app/src/python/pinerylabs/runbooks/models/team.py", line 151, in _l
Apr 28 10:26:22 MainThread [ERRO]           oad_graph
Apr 28 10:26:22 MainThread [ERRO]         for member in self.members:
Apr 28 10:26:22 MainThread [ERRO]       File "/app/src/python/pinerylabs/runbooks/models/team.py", line 99, in mem
Apr 28 10:26:22 MainThread [ERRO]           bers
Apr 28 10:26:22 MainThread [ERRO]         return self.get_child("members", lambda: list(self.box.team_members.find
Apr 28 10:26:22 MainThread [ERRO]             _by_team(self.id)))
Apr 28 10:26:22 MainThread [ERRO]       File "/app/src/python/pinerylabs/orm/model.py", line 540, in get_child
Apr 28 10:26:22 MainThread [ERRO]         self._children[field_name] = doLoad()
Apr 28 10:26:22 MainThread [ERRO]       File "/app/src/python/pinerylabs/runbooks/models/team.py", line 99, in <la
Apr 28 10:26:22 MainThread [ERRO]           mbda>
Apr 28 10:26:22 MainThread [ERRO]         return self.get_child("members", lambda: list(self.box.team_members.find
Apr 28 10:26:22 MainThread [ERRO]             _by_team(self.id)))
Apr 28 10:26:22 MainThread [ERRO]       File "/app/src/python/pinerylabs/orm/model_box.py", line 511, in select_qu
Apr 28 10:26:22 MainThread [ERRO]           ery
Apr 28 10:26:22 MainThread [ERRO]         if result.can_read:
Apr 28 10:26:22 MainThread [ERRO]       File "/app/src/python/pinerylabs/orm/model.py", line 94, in can_read
Apr 28 10:26:22 MainThread [ERRO]         return self.box.can_read(self.id)
Apr 28 10:26:22 MainThread [ERRO]       File "/app/src/python/pinerylabs/runbooks/models/team_member.py", line 84,
Apr 28 10:26:22 MainThread [ERRO]            in can_read
Apr 28 10:26:22 MainThread [ERRO]         viewer = self.derive_viewer(user)
Apr 28 10:26:22 MainThread [ERRO]       File "/app/src/python/pinerylabs/orm/model_box.py", line 588, in derive_vi
Apr 28 10:26:22 MainThread [ERRO]           ewer
Apr 28 10:26:22 MainThread [ERRO]         raise RuntimeError("cannot assess permissions because this model box has
Apr 28 10:26:22 MainThread [ERRO]              no viewer")
Apr 28 10:26:22 MainThread [ERRO]     RuntimeError: cannot assess permissions because this model box has no viewer
Apr 28 10:26:22 MainThread [ERRO]     
Apr 28 10:26:22 at=info method=GET path="/api/teams?slug=stockx&graph=full" host=api.runbooks.app request_id=a28a763d-4ab1-41f8-b299-aed508a3c383 fwd="73.34.233.233" dyno=web.1 connect=1ms service=275ms status=500 bytes=659 protocol=https
Apr 28 10:26:22 MainThread [INFO] <<< GET /api/teams: 500 INTERNAL SERVER ERROR with 174b in 244ms
```

**Comment by andrewminer** [comment]
Similar to #272
